=== ismailktami/metamodelisation-jftl2025/cypress-exampes/cypress/fixtures/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Create Account Form Schema",
  "type": "object",
  "properties": {
    "formName": {
      "type": "string"
    },
    "formLink": {
      "type": "string",
      "format": "uri"
    },
    "fields": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "required": {
            "type": "boolean"
          },
          "regex": {
            "type": "string"
          }
        },
        "required": ["id", "type", "required"]
      }
    },
    "actions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "alias": {
            "type": "string"
          },
          "data-testid": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "defaultState": {
            "type": "string",
            "enum": ["enabled", "disabled"]
          }
        },
        "required": ["alias", "data-testid", "label", "defaultState"]
      }
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "conditionType": {
            "type": "string",
            "enum": [
              "ALL_FIELDS_VALID",
              "ANY_FIELD_INVALID",
              "ANY_FIELD_EMPTY"
            ]
          },
          "fields": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "actionStates": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "alias": {
                  "type": "string"
                },
                "state": {
                  "type": "string",
                  "enum": ["enabled", "disabled"]
                }
              },
              "required": ["alias", "state"]
            }
          }
        },
        "required": ["conditionType", "actionStates"]
      }
    }
  },
  "required": ["formName", "formLink", "fields", "actions", "rules"]
}

=== ismailktami/metamodelisation-jftl2025/cypress/fixtures/accountFormWithoutData.json
{
  "formName": "Create Account",
  "formLink": "http://127.0.0.1:5500/cypress/formulaires/CreateAccount.html",
  "fields": [
    { "id": "firstName", "type": "input", "required": true, "regex": "^[A-Z][a-z]{1,50}$" }, 
    { "id": "lastName", "type": "input", "required": true, "regex": "^[A-Z][a-z]{1,50}$" }
  ],
  "actions": [
      { "alias": "submit", "data-testid": "create-account-btn", "label": "Créer un compte", "defaultState": "disabled" }
    , { "alias": "reset", "data-testid": "reset-btn", "label": "Réinitialiser", "defaultState": "disabled" }
  ],
  "rules": [
    {
      "conditionType": "ALL_FIELDS_VALID",
      "actionStates": [{"alias": "submit", "state": "enabled"},{"alias": "reset", "state": "enabled"}]},
    {
      "conditionType": "ANY_FIELD_INVALID",
      "fields": ["lastName","age", "email", "password"],
      "actionStates": [ {"alias": "submit", "state": "disabled"}, {"alias": "reset", "state": "enabled"} ] },
    {
      "conditionType": "ANY_FIELD_EMPTY",
      "fields": ["lastName","age","email", "password"],
      "actionStates": [ {"alias": "submit", "state": "disabled"}, {"alias": "reset", "state": "enabled"} ]}
  ]
}

=== ismailktami/metamodelisation-jftl2025/cypress-exampes/cypress/integration/formTestsWithoutDatas/accountFormWithoutDatas.json
{
  "formName": "Create Account",
  "formLink": "http://127.0.0.1:5500/cypress-exampes/cypress/formulaires/CreateAccount.html",
  "fields": [
    { "id": "firstName", "type": "input", "required": true, "regex": "^[A-Z][a-z]{2,10}$" },
    { "id": "lastName", "type": "input", "required": true, "regex": "^[A-Z][a-z]{2,15}$" },
    { "id": "gender", "type": "select", "required": true, "options": ["Male", "Female", "Other"] },
    { "id": "age", "type": "number", "required": true, "min": 18, "max": 100 },
    { "id": "email", "type": "email", "required": true, "regex": "^[a-z0-9._%+-]+@[a-z0-9-]+\\.[a-z]{2,}$" },
    { "id": "username", "type": "input", "required": true, "regex": "^[A-Z][a-z]{5,30}$" },
    { "id": "password", "type": "password", "required": true, "regex": "^[A-Z][a-z]{15,30}$" }
  ],
  "actions": [
      { "alias": "submit", "data-testid": "create-account-btn", "label": "Créer un compte", "defaultState": "disabled" }
    , { "alias": "reset", "data-testid": "reset-btn", "label": "Réinitialiser", "defaultState": "disabled" }
  ],
  "rules": [
    {
      "conditionType": "ALL_FIELDS_VALID",
      "actionStates": [{"alias": "submit", "state": "enabled"},{"alias": "reset", "state": "enabled"}]},
    {
      "conditionType": "ANY_FIELD_INVALID",
      "fields": ["lastName","age", "email", "password","username"],
      "actionStates": [ {"alias": "submit", "state": "disabled"}, {"alias": "reset", "state": "enabled"} ] },
    {
      "conditionType": "ANY_FIELD_EMPTY",
      "fields": ["lastName","age","email", "password"],
      "actionStates": [ {"alias": "submit", "state": "disabled"}, {"alias": "reset", "state": "enabled"} ]}
  ]
}
